### ISSUE TITLE
minor spelling error in fastlane structure

### ISSUE THREAD

**Issue by IzzySoft** [TecCheck/FastLyrics#1]
Please note that the locale must be `en-US` to be picked up properly, yours currently is `en-Us` (with a lower-case `s`).

**Comment by TecCheck** [comment]
Oh that's embarrassing. I'll fix that

**Comment by TecCheck** [comment]
Fixed it in c72b07c

**Comment by IzzySoft** [comment]
Well, that was fast – thanks! So I've removed my local work-around (symlink) and updated to your change.

For some background: I've just added your app to my repo, where it will [show up](https://apt.izzysoft.de/packages/io.github.teccheck.fastlyrics/) with the next sync around 6 pm UTC. You're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your readme if you wish.

Btw: you will see it carries the NonFreeNet anti-feature. I don't know where the lyrics are fetched from; I'm happily proven wrong and you found a real FOSS service for that – if so, please point out and I'll remove the AF. If not, it's not a show-stopper; people are used to this specific one for such services, so it's rather for transparency.

And no need to be embarrassed. My keyboard fools me all the time, forgetting a letter here and there I'm sure having typed. The good thing with FOSS: someone™ will notice and let you know, usually :smile:

**Comment by TecCheck** [comment]
That's very cool. Thank you so much. The lyrics come from [Genius](https://genius.com), a rather well know site for lyrics. Sadly, it's not free, so I added the AF and that's fine with me that way. Afterall transparency is the way

> And no need to be embarrassed. My keyboard fools me all the time...

If you say so :D

**Comment by IzzySoft** [comment]
Thanks for the update – and for the transparency!
