### ISSUE TITLE
Fastlane: German short_description.txt too long

### ISSUE THREAD

**Issue by IzzySoft** [TecCheck/FastLyrics#12]
Fastlane `short_description.txt` is limited to 80 chars, everything beyond is simply cut off. Your German one currently has 86 chars, so the end will be cut (probably mid-word). Could you please shorten it a bit? Suggestion (from a native speaker):

```
lädt automatisch Songtexte zum aktuell laufenden Song herunter und zeigt sie an
```

Thanks!

**Comment by TecCheck** [comment]
Updated it. Thanks a lot

**Comment by IzzySoft** [comment]
Thank you!
