### ISSUE TITLE
feature request: synced lyrics

### ISSUE THREAD

**Issue by tubbadu** [TecCheck/FastLyrics#19]
It would be awesome to have the ability to sync the lyric to the currently playing song, similar to what musixmatch do. It could be useful [lrcget](https://github.com/tranxuanthang/lrcget) to achieve this (with its [API](https://github.com/tranxuanthang/lrcget/issues/2))

**Comment by TecCheck** [comment]
Yes that'd be cool. I've started to work on it. However other things have cropped up so I'm not really doing much with FastLyrics. When I eventually feel like doing more, I will implement this next

**Comment by TecCheck** [comment]
As mentioned in #13 this is now implemented. Hope you like it

**Comment by tubbadu** [comment]
Awesome! I love this!
