### ISSUE TITLE
Problem in notification permission 

### ISSUE THREAD

**Issue by j2a1ck** [TecCheck/FastLyrics#27]
![Screenshot_20240131-223105.png](https://github.com/TecCheck/FastLyrics/assets/103171016/0f5a8c77-0bfd-47b5-85c9-cc89d0ffbef0)

![Screenshot_20240131-223110.png](https://github.com/TecCheck/FastLyrics/assets/103171016/79a1c28c-9354-431f-833f-66112d8166f0)

I have pixel os 
Android 14

**Comment by TecCheck** [comment]
Have a look at #6. It might help. Unfortunately, I don't have a phone that restricts those settings

**Comment by j2a1ck** [comment]
> Have a look at #6. It might help. Unfortunately, I don't have a phone that restricts those settings

It solved the problem
Thank you
