### ISSUE TITLE
[question] How to create new genius api access token?

### ISSUE THREAD

**Issue by shub39** [TecCheck/FastLyrics#38]
Hello. Inspired from your app I am making my own app in compose to search and get lyrics for practice. I made a new app from [here](https://genius.com/api-clients), but the access token is only providing the search results. Trying with your token the lyrics are obtained. what is the process for obtaining an access token that provides lyrics? I searched and could not find an answer. please help.

**Comment by shub39** [comment]
I see. Thanks for the response

**Comment by shub39** [comment]
@TecCheck Sorry to disturb you again. I searched everywhere and could not find anything related to a paid access token. Apparently its very [hard](https://genius.com/discussions/481170-Get-lyrics-on-smart-link-creator). Can i use your token for now?

**Comment by TecCheck** [comment]
That's fine by me

**Comment by shub39** [comment]
Thanks! although i am directly scraping the url from search for lyrics. its slow but does the job. 
https://github.com/shub39/Rush
