### ISSUE TITLE
Fetching Lyrics Error

### ISSUE THREAD

**Issue by HonestAbe7** [TecCheck/FastLyrics#4]
Thanks for updating this app so quickly and solving it from crashing.

The following is a screenshot of the error message I get when I try playing a song. I have tried several songs too.
![Screenshot_20230519-141750](https://github.com/TecCheck/FastLyrics/assets/88217236/e4cd7793-9dbf-4052-9e91-857ecff6b780)

**Comment by HonestAbe7** [comment]
Solved! It was on my end. I accidentally disabled the api.genuis.com essential tracker. Works great! 😁

**Comment by TecCheck** [comment]
Okey, thats good to see :D
