### ISSUE TITLE
Notifications are restricted

### ISSUE THREAD

**Issue by pedr0m9** [TecCheck/FastLyrics#6]
Can't seem to be able to allow notification access, it's just greyed out and won't allow me to turn it on.
![Screenshot_20230520-131141_Settings](https://github.com/TecCheck/FastLyrics/assets/82251846/dfe7ee4f-8c2a-4180-9d85-600e085754df)
![Screenshot_20230520-131144_Settings](https://github.com/TecCheck/FastLyrics/assets/82251846/94ab8c42-cf63-4e21-9b64-9b0f5ec8e4ec)

**Comment by pedr0m9** [comment]
Nevermind, I figured it out, thanks.

**Comment by TecCheck** [comment]
Other people have the same problem as you. How did you solve it?

**Comment by pedr0m9** [comment]
In this screen, there should be 3 dots on the upper right corner to allow restricted settings. The you click that and that's it.
![Screenshot_20230523-141328_Settings](https://github.com/TecCheck/FastLyrics/assets/82251846/8dcec36a-00e2-4e75-ae7a-9cc9a727cb45)

But for me it just would not appear for wathever reason, then you get this screen that the app takes you to 
![Screenshot_20230523-141637_Settings](https://github.com/TecCheck/FastLyrics/assets/82251846/5839051f-7996-4b0e-aa12-17edf2c2556f)
And it will probably be greyed out, asking for advanced permission, so just click the icon of the app and the 3 dots should appear, or i think.
