### ISSUE TITLE
Way to use the clipboard within the app

### ISSUE THREAD

**Issue by pedr0m9** [TecCheck/FastLyrics#7]
Is it possible to make the app compatible with the clipboard? 
to easily copy the lyrics
Or a button on top that copies all the text with in that song, thank you

**Comment by TecCheck** [comment]
That shouldn't be too hard to implement

**Comment by TecCheck** [comment]
I have implemented a button to copy lyrics to the clipboard in commit c7692a6

**Comment by pedr0m9** [comment]
Awesome

**Comment by pedr0m9** [comment]
you're amazung dude
