### ISSUE TITLE
Unable to load manually searched lyrics

### ISSUE THREAD

**Issue by stemy2** [TecCheck/FastLyrics#8]
Hello,

I'm listening a song for wich the app is unable to find the lyrics automatically. So i used the manual search and the app found it successfully, but after clicking on the result, it did nothing but loading indefinitely, as if the connection was suddenly down (it wasn't).

**Comment by TecCheck** [comment]
I've notice that some songs tend to load indefinitely. Just to be sure, did you try to search for something different?

**Comment by TecCheck** [comment]
Oh and it would be awesome if you could post a log (if you can)

**Comment by stemy2** [comment]
Unfortunately, i don't know how to post a log, bu i think it would be clearer with screenshots.

1) It can't find my song.
![Screenshot_20230523-114919_FastLyrics](https://github.com/TecCheck/FastLyrics/assets/22192600/47b7f8c2-d33c-40da-9f9d-8aa5899ced5b)
2) Searched successfully with the manual search tool.
![Screenshot_20230523-114943_FastLyrics](https://github.com/TecCheck/FastLyrics/assets/22192600/51c63396-80b1-4a6e-b1ea-132e3f558459)
3) Clicked on the first result, and the load icon seems to spin forever.
![Screenshot_20230523-114956_FastLyrics](https://github.com/TecCheck/FastLyrics/assets/22192600/ee1180cf-14b9-440a-89be-b92109a34ecc)
